### ISSUE TITLE
Doesn't work with SQLite

### ISSUE THREAD

**Issue by jhutchins** [dropwizard/dropwizard-flyway#2]
I'm using `io.dropwizard:dropwizard-core:0.7.0`, `io.dropwizard.modules:dropwizard-flyway:0.7.0-1`, and `org.xerial:sqlite-jdbc:3.8.7`

The database configuration looks like this
```yaml
# Database settings
database:
  # the name of your JDBC driver
  driverClass: org.sqlite.JDBC

  # the JDBC URL
  url: jdbc:sqlite:dev.db

  # the JDBC user
  user: jhutchins
```

When trying to run a migrate command
```
java -jar application/build/libs/application-all-0.1.0.jar db migrate ./dev.yml
```
I get the following output
```syslog
INFO  [2015-01-01 18:02:00,397] org.flywaydb.core.internal.dbsupport.DbSupportFactory: Database: jdbc:sqlite:dev.db (SQLite 3.0)
INFO  [2015-01-01 18:02:00,581] org.flywaydb.core.internal.command.DbMigrate: Current version of schema "main": << Empty Schema >>
INFO  [2015-01-01 18:02:00,581] org.flywaydb.core.internal.command.DbMigrate: Migrating schema "main" to version 1
Exception in thread "main" org.flywaydb.core.api.FlywayException: Unable to commit transaction
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:76)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:285)
	at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:46)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:207)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:864)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:811)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1171)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:811)
	at io.dropwizard.flyway.cli.DbMigrateCommand.run(DbMigrateCommand.java:76)
	at io.dropwizard.flyway.cli.DbCommand.run(DbCommand.java:48)
	at io.dropwizard.flyway.cli.AbstractFlywayCommand.run(AbstractFlywayCommand.java:45)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:72)
	at com.nti.flow.Flow.main(Flow.java:29)
ERROR [2015-01-01 18:02:06,606] org.flywaydb.core.internal.util.jdbc.TransactionTemplate: Unable to restore autocommit to original value for connection
! java.sql.SQLException: database is locked
! at org.sqlite.core.DB.throwex(DB.java:859) ~[application-all-0.1.0.jar:0.1.0]
! at org.sqlite.core.DB.exec(DB.java:142) ~[application-all-0.1.0.jar:0.1.0]
! at org.sqlite.jdbc3.JDBC3Connection.setAutoCommit(JDBC3Connection.java:152) ~[application-all-0.1.0.jar:0.1.0]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0]
! at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0]
! at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126) ~[application-all-0.1.0.jar:0.1.0]
! at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109) ~[application-all-0.1.0.jar:0.1.0]
! at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80) ~[application-all-0.1.0.jar:0.1.0]
! at com.sun.proxy.$Proxy28.setAutoCommit(Unknown Source) ~[na:na]
! at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:96) [application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:285) [application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:46) [application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:207) [application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156) [application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72) [application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156) [application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.Flyway$1.execute(Flyway.java:864) [application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.Flyway$1.execute(Flyway.java:811) [application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.Flyway.execute(Flyway.java:1171) [application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.Flyway.migrate(Flyway.java:811) [application-all-0.1.0.jar:0.1.0]
! at io.dropwizard.flyway.cli.DbMigrateCommand.run(DbMigrateCommand.java:76) [application-all-0.1.0.jar:0.1.0]
! at io.dropwizard.flyway.cli.DbCommand.run(DbCommand.java:48) [application-all-0.1.0.jar:0.1.0]
! at io.dropwizard.flyway.cli.AbstractFlywayCommand.run(AbstractFlywayCommand.java:45) [application-all-0.1.0.jar:0.1.0]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [application-all-0.1.0.jar:0.1.0]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [application-all-0.1.0.jar:0.1.0]
! at io.dropwizard.Application.run(Application.java:72) [application-all-0.1.0.jar:0.1.0]
! at com.nti.flow.Flow.main(Flow.java:29) [application-all-0.1.0.jar:0.1.0]
Caused by: java.sql.SQLException: database is locked
	at org.sqlite.core.DB.throwex(DB.java:859)
	at org.sqlite.core.DB.exec(DB.java:142)
	at org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ERROR [2015-01-01 18:02:06,607] org.flywaydb.core.internal.command.DbMigrate: Migration of schema "main" to version 1 failed! Changes successfully rolled back.
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80)
	at com.sun.proxy.$Proxy28.commit(Unknown Source)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:73)
	... 17 more
ERROR [2015-01-01 18:02:06,607] io.dropwizard.flyway.cli.AbstractFlywayCommand: Error while running database command
! java.sql.SQLException: database is locked
! at org.sqlite.core.DB.throwex(DB.java:859) ~[application-all-0.1.0.jar:0.1.0]
! at org.sqlite.core.DB.exec(DB.java:142) ~[application-all-0.1.0.jar:0.1.0]
! at org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:162) ~[application-all-0.1.0.jar:0.1.0]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0]
! at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0]
! at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126) ~[application-all-0.1.0.jar:0.1.0]
! at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109) ~[application-all-0.1.0.jar:0.1.0]
! at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80) ~[application-all-0.1.0.jar:0.1.0]
! at com.sun.proxy.$Proxy28.commit(Unknown Source) ~[na:na]
! at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:73) ~[application-all-0.1.0.jar:0.1.0]
! ... 17 common frames omitted
! Causing: org.flywaydb.core.api.FlywayException: Unable to commit transaction
! at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:76) ~[application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:285) ~[application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:46) ~[application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:207) ~[application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156) ~[application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72) ~[application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156) ~[application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.Flyway$1.execute(Flyway.java:864) ~[application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.Flyway$1.execute(Flyway.java:811) ~[application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.Flyway.execute(Flyway.java:1171) ~[application-all-0.1.0.jar:0.1.0]
! at org.flywaydb.core.Flyway.migrate(Flyway.java:811) ~[application-all-0.1.0.jar:0.1.0]
! at io.dropwizard.flyway.cli.DbMigrateCommand.run(DbMigrateCommand.java:76) ~[application-all-0.1.0.jar:0.1.0]
! at io.dropwizard.flyway.cli.DbCommand.run(DbCommand.java:48) ~[application-all-0.1.0.jar:0.1.0]
! at io.dropwizard.flyway.cli.AbstractFlywayCommand.run(AbstractFlywayCommand.java:45) ~[application-all-0.1.0.jar:0.1.0]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [application-all-0.1.0.jar:0.1.0]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [application-all-0.1.0.jar:0.1.0]
! at io.dropwizard.Application.run(Application.java:72) [application-all-0.1.0.jar:0.1.0]
! at com.nti.flow.Flow.main(Flow.java:29) [application-all-0.1.0.jar:0.1.0]
```

**Comment by joschi** [comment]
Could you please retry with another SQLite JDBC driver like https://code.google.com/p/sqlite4java/ or http://sqljet.com/ to rule out a problem with the [Xerial SQLite JDBC driver](https://bitbucket.org/xerial/sqlite-jdbc)?

**Comment by joschi** [comment]
No update from original poster. Closing issue.
